### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by kirupakaran369** [romibuzi/majordome#10]
I have created this application dockerized, the issue is aws data can't fetch the dashboard, but locathost working

**Comment by romibuzi** [comment]
hey @kirupakaran369, great job ! did you share AWS credentials in the docker container, either with environment variables : 
AWS_ACCESS_KEY_ID='...'
AWS_SECRET_ACCESS_KEY='...'

or by sharing `~/.aws/credentials` file

**Comment by kirupakaran369** [comment]
sure @romibuzi .

**Comment by romibuzi** [comment]
Ok great, the main challenge is that the docker image is needed for both the AWS crawling part and for the web interface. But both need to share the sqlite database. I will see if i can come with a solution for that

**Comment by romibuzi** [comment]
I succeed to dockerized the application here https://github.com/romibuzi/majordome/pull/11. Instructions can be found in README https://github.com/romibuzi/majordome#docker to build and launch app through docker :)
